### ISSUE TITLE
Vimeo version?

### ISSUE THREAD

**Issue by creativesuspects** [limbo-works/Limbo.Umbraco.YouTube#1]
Great package! I'd love to see a Vimeo version of this package. More and more clients are moving away from YouTube due to GDPR issues.

Edit: Just noticed your DreamBroker package. Very interesting!

**Comment by abjerner** [comment]
Hi @creativesuspects 

There is a Vimeo version here: https://github.com/limbo-works/Limbo.Umbraco.Vimeo
